version = 1

exclude_patterns = [
  "src/utils/youtube-notifier/**",
  "build.mjs",
  "jest.config.js",
  "__tests__/**"
]

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
environment = ["nodejs"]
